### ISSUE TITLE
Simplify

### ISSUE THREAD

**Issue by jetaggart** [pgrunde/g3-assessment-week-6#5]
https://github.com/pgrunde/g3-assessment-week-6/blob/master/lib/G3.rb#L9-L13

can look like

``` ruby
return_hash.store(hash[:id], hash)
```

You're copying the array unnecessarily.

**Comment by pgrunde** [comment]
Excellent - so run down is to avoid copying the array, pass the data
directly on initialize, remove 'require "capybara/rspec"'
